### ISSUE TITLE
Installation fails with "error"

### ISSUE THREAD

**Issue by dawiinci** [mjoshd/hyperhdr-ha#13]
## Version of the custom_component
0.0.6

Tested with HyperHDR 17.0.0.0 and 18.0.0.0b2

## Configuration

I just wanted to add the integration in the frontend, but it fails to configure.

## Describe the bug
I can get a token which is shown in HyperHDR but in the next step the integration just shows "error". 

Logs

```
Logger: aiohttp.server
Source: custom_components/hyperhdr/config_flow.py:401 
Integration: HyperHDR (documentation, issues) 
First occurred: 14:58:16 (2 occurrences) 
Last logged: 14:59:28

Error handling request
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 635, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is found, but chunk is longer than limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/server/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/Users/server/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/Users/server/homeassistant-config/custom_components/hyperhdr/config_flow.py", line 234, in async_step_user
    return await self._advance_to_auth_step_if_necessary(
  File "/Users/server/homeassistant-config/custom_components/hyperhdr/config_flow.py", line 141, in _advance_to_auth_step_if_necessary
    return await self.async_step_confirm()
  File "/Users/server/homeassistant-config/custom_components/hyperhdr/config_flow.py", line 401, in async_step_confirm
    async with self._create_client() as hyperhdr_client:
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 149, in __aenter__
    result = await self.async_client_connect()
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 369, in async_client_connect
    await self.async_client_disconnect()
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 422, in async_client_disconnect
    return await self._async_client_disconnect_internal()
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 451, in _async_client_disconnect_internal
    await self._await_or_stop_task(receive_task, stop_task=True)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 588, in _await_or_stop_task
    await task
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 568, in _receive_task_loop
    while await self._async_receive_once():
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 608, in _async_receive_once
    resp_json = await self._async_safely_read_command(use_timeout=False)
  File "/Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py", line 485, in _async_safely_read_command
    resp = await asyncio.wait_for(future_resp, timeout=timeout_secs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 549, in readline
    raise ValueError(e.args[0])
ValueError: Separator is found, but chunk is longer than limit

```

**Comment by dawiinci** [comment]
Under Token management inside Network services are entries from Home Assistant. They are made by going to hyperhdr frontend. This is probably an automatic feature of HA.

I have these settings enabled:
- API Authentication
- Local Admin API Authentication
- Local API Authentication

Mainly because it wasn't working without that. Should I configure using yaml? If so, how?

**Comment by mjoshd** [comment]
Thank you for the explanation of how you are setting up tokens. 

I have never tokens before and I was able to do some testing today however I was unable to replicate the error shown in your logs.

I typically use the default settings shown below:
![image](https://user-images.githubusercontent.com/35782597/168153200-ea6d36bf-593e-4791-9be9-ced2c2d55f45.png)

I discovered that the tokens are required after "Local API Authentication" is enabled.
After enabling Local API Authentication and clicking save I set up the integration in two different ways
- clicking the "Automatically create new token" box
- manually creating a token and entering it into the "Or provide pre-existing token" field

Both attempts were successful
![image](https://user-images.githubusercontent.com/35782597/168151182-8dd62358-bd77-4234-9f5c-d13dd5fedad8.png)

The only way I was able to force a failure during the setup was to block HyperHDR from communicating using the firewall of the system it is running on. This did cause the setup to fail but resulted in a very different Home Assistant log message:
`2022-05-12 14:59:52 WARNING (MainThread) [hyperhdr.client] Failed HyperHDR (192.168.41.41:19444) command: {'command': 'sysinfo', 'error': 'No Authorization', 'success': False, 'tan': 1}`

Afterward, I removed the block in the firewall then went through setup again and it worked without issue.

The only things I can think of for you to check and/or try are:
- make sure whatever device Home Assistant is running on does not have any firewall rules that could be blocking communication to HyperHDR (if you are running Home Assistant OS then this is probably not the issue).
- make sure whatever device HyperHDR is running on does not have any firewall rules that could be blocking communication to Home Assistant.
- make sure nothing on your network is blocking communication between Home Assistant and HyperHDR (e.g. rules in PiHole, AdGuard, PFSense, vLAN restrictions, etc).
- if all else fails, set up two virtual machines with an open network between them (1-Home Assistant, 1-HyperHDR) follow the "manual" setup instructions for the integration and try to get Home Assistant & HyperHDR to communicate. Once successful, replicate that connection on your real network/Home Assistant/HyperHDR.

**Comment by mjoshd** [comment]
Sorry, forgot to answer your last question in my long reply. There is not a way to set up the integration using yaml.

**Comment by dawiinci** [comment]
Thanks. It is, however,  still not working. 

```
Logger: hyperhdr.client
Source: /Users/server/homeassistant/lib/python3.9/site-packages/hyperhdr/client.py:624 
First occurred: 20:17:34 (7 occurrences) 
Last logged: 20:18:40

Failed HyperHDR (localhost:19444) command: {'command': 'authorize', 'error': 'Errors during specific message validation, please consult the HyperHDR Log', 'success': False, 'tan': 1}
Failed HyperHDR (localhost:19444) command: {'command': 'authorize-requestToken', 'error': 'Token request timeout or denied', 'success': False, 'tan': 1}

```

**Comment by mjoshd** [comment]
I see the IP address you entered was actually a hostname? e.g. localhost

What device are you using to host HyperHDR?

**Comment by dawiinci** [comment]
I am on macOS. And I tried the ip as well.

**Comment by mjoshd** [comment]
What is your Home Assistant running on?

I still think something on the HyperHDR host (your mac) is blocking communications.

As a fairly simple test, please try setting up the [HyperHDR addon](https://github.com/ihrapsa/hassio-addons#installation-instructions) in Home Assistant and connecting my integration to it. I just now tested setting up my integration with that addon and it worked perfectly.

After installing and starting the addon visit its webpage to make sure it is running but don't change any settings, then set up my integration ([manual setup](https://github.com/mjoshd/hyperhdr-ha#manually-not-recommended) is fine for a 1-off test) and just provide the LAN IP address of your Home Assistant instance.

If the test works then it points to your mac as being the source of the communication issue. I do not have a mac so I don't know how to help further with that.

If the test doesn't work then it points to something in your Home Assistant configuration as the culprit and I would ask that you follow the instructions to set up a fresh [Virtual Machine of Home Assistant OS](https://www.home-assistant.io/installation/macos) (don't import a backup, just set it up as basic as possible) then install the addon linked above and set up my integration to verify connectivity/functionality.

These tests should help to narrow down where the issue may be coming from; please let me know the results.

If all of the above tests still fail then I'm not sure how to be of further help as I cannot reproduce a setup failure without intentionally blocking communication between Home Assistant and HyperHDR.

**Comment by dawiinci** [comment]
Everything is running on the same Mac. I use Core (python venv) installation, so the addon can’t be used. 

Thanks for your help though.
