### ISSUE TITLE
camera steam error

### ISSUE THREAD

**Issue by ocerot** [mjoshd/hyperhdr-ha#3]
此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/hyperhdr/camera.py:202 
Integration: HyperHDR (documentation, issues) 
First occurred: 00:24:07 (49 occurrences) 
Last logged: 11:15:47

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/hyperhdr/camera.py", line 209, in _image_streaming
    yield await self._start_image_streaming_for_client()
  File "/config/custom_components/hyperhdr/camera.py", line 192, in _start_image_streaming_for_client
    self.is_streaming = True
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 629, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 668, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/hyperhdr/camera.py", line 224, in handle_async_mjpeg_stream
    async with self._image_streaming() as is_streaming:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/config/custom_components/hyperhdr/camera.py", line 211, in _image_streaming
    await self._stop_image_streaming_for_client()
  File "/config/custom_components/hyperhdr/camera.py", line 202, in _stop_image_streaming_for_client
    self.is_streaming = False
AttributeError: can't set attribute

**Comment by zigomatichub** [comment]
Hello, I'm also having exactly the same error message. 

HA is in 2021.12.10 with HyperHDR (17.0.0.0)

**Comment by mjoshd** [comment]
I did some investigation while I was on a break at work and it appears that the Hyperion integration (which this is pretty much a copy of with alterations specific to HyperHDR's API) has had some changes. 

I won't be able to look closely at it until the weekend but I will try to get to it.

If all goes well then you'll see an update available in HACS after I get everything updated.

**Comment by zigomatichub** [comment]
In debug , before the ERROR, I received this:
2022-01-19 17:51:58 DEBUG (MainThread) [hyperhdr.client] Read from server (10.0.4.14:19444): b'{"command":"ledcolors-imagestream-start","success":true,"tan":0}\n'
2022-01-19 17:51:58 DEBUG (MainThread) [hyperhdr.client] Read from server (10.0.4.14:19444): b'{"command":"ledcolors-imagestream-stop","success":true,"tan":0}\n'

**Comment by mjoshd** [comment]
@ocerot @zigomatichub 

Pretty sure this is solved so I'm going to close this for now 🎉 

If you don't see the v0.0.3 update in HACS just restart Home Assistant and it should show up.

Don't forget to restart again after installing the update 😺

**Comment by mjoshd** [comment]
Try out v0.0.4
The camera entity is now removed (it was just too buggy and unreliable).
The release notes describe how to remove the orphaned camera entity.
